### PR TITLE
Update azuredeploy.json

### PR DESCRIPTION
**Pull request by mimig1**
Current template will not deploy. Making updates as per email w/Alicia.

### CODE REVIEW

**Comment by mimig1** [comment]
@hrasheed-msft FYI - Making this change so that the template works and can be used in the next Learn module.

**Comment by mimig1** [comment]
#sign-off

**Comment by mimig1** [comment]
@Blackmist - Hi! Can you approve this?

**Comment by Blackmist** [comment]
Hi @mimig1 I haven't worked on HDInsight in a while, so probably not the most qualified to approve or review. I believe @hrasheed-msft is maintaining this repo currently and should review before merger.

**Comment by hrasheed-msft** [comment]
@mimig1 Sorry for the delay. Changes look good. Thanks.

**Pull request merged**
